repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.16.8
      hooks:
          - id: ruff-check
            args:
                - --fix
                - --exit-non-zero-on-fix
          - id: ruff-format
    - repo: local
      hooks:
          - id: typecheck
            name: typecheck
            language: system
            entry: uv run mypy .
            types: [python]
            exclude: ^tests
            require_serial: true
    - repo: builtin
      hooks:
          - id: check-yaml
            args:
                - --allow-multiple-documents
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
