[project]
name = "aiohttp-asgi-connector"
version = "1.1.3"
description = "AIOHTTP Connector for running ASGI applications"
authors = [{ name = "Elias Gabriel", email = "oss@eliasfgabriel.com" }]
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.1.0; python_version >= '3.9'",
    "aiohttp<3.11,>=3.1.0; python_version ~= '3.8.0'",
]
keywords = [
    "fastapi",
    "aiohttp",
    "asgi",
    "testing",
    "starlette",
    "httpx",
    "asyncio",
]
readme = "README.md"
license = { text = "BSD-3-Clause" }

[dependency-groups]
dev = [
    "fastapi",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "python-multipart",
]
local = [
    "mypy",
    "prek",
    "typing-extensions",
]

[tool.pytest.ini_options]
addopts = "-ra -vv -p 'no:anyio' --cov aiohttp_asgi_connector --import-mode=importlib"
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.ruff]
unsafe-fixes = false

[tool.ruff.lint]
extend-select = ["ANN", "ASYNC", "PYI", "PT", "SIM", "TID", "PERF", "TRY", "PGH003"]
extend-ignore = ["TID252", "TRY003", "TRY300"]
preview = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true

[tool.mypy]
strict = true

[tool.pyright]
ignore = ["tests"]

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
